---
- name: Ensure unzip is installed
  become: true
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 3600  # Do not update if already done in the last hour.
    pkg:
      - unzip
  tags:
    - nordvpn

- name: Ensure OpenVPN is installed
  become: true
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 3600  # Do not update if already done in the last hour.
    pkg:
      - openvpn
  tags:
    - nordvpn

- name: Ensure /etc/openvpn/nordvpn/ exists
  become: true
  ansible.builtin.file:
    state: directory
    path: /etc/openvpn/nordvpn/
    mode: u=rx,g=rx,o=
  tags:
    - nordvpn

- name: Ensure credentials file
  become: true
  ansible.builtin.template:
    src: templates/credentials.cred.j2
    dest: /etc/openvpn/nordvpn/credentials.cred
    owner: root
    group: root
    mode: u=r,g=r,o=
  tags:
    - nordvpn

- name: Download OpenVPN configurations
  become: true
  ansible.builtin.get_url:
    url: "{{ nordvpn__openvpn_url }}"
    dest: "/etc/openvpn/nordvpn/ovpn.zip"
    force: true
    owner: root
    group: root
    mode: u=r,g=,o=
  register: downloaded_openvpn_configurations
  tags:
    - nordvpn

- name: Extract OpenVPN configurations
  become: true
  ansible.builtin.unarchive:
    remote_src: true
    src: /etc/openvpn/nordvpn/ovpn.zip
    dest: /etc/openvpn/nordvpn/
    owner: root
    group: root
    mode: u=r,g=r,o=
  when: downloaded_openvpn_configurations.changed
  tags:
    - nordvpn

# Note: Change profile before copying to ensure idempotence
- name: Ensure credentials file is referenced in wanted profile
  become: true
  ansible.builtin.lineinfile:
    path: "{{ nordvpn__config }}"
    regexp: '^auth-user-pass'
    line: 'auth-user-pass /etc/openvpn/nordvpn/credentials.cred'
    owner: root
    group: root
    mode: u=r,g=r,o=
  tags:
    - nordvpn

- name: Ensure wanted OpenVPN configuration is active
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: "{{ nordvpn__config }}"
    dest: /etc/openvpn/client/active.conf
    owner: root
    group: root
    mode: u=r,g=r,o=
  notify: Restart openvpn
  tags:
    - nordvpn

- name: Ensure /opt/vpn-manager exists
  become: true
  ansible.builtin.file:
    state: directory
    path: /opt/vpn-manager
    mode: u=rwx,g=rwx,o=rwx
  tags:
    - nordvpn

- name: Ensure VPN managing scripts
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /opt/vpn-manager/
    owner: root
    group: root
    mode: u=rwx,g=rwx,o=rwx
  loop:
    - routing-add-default-gateway.sh
    - routing-delete-default-gateway.sh
    - routing-add-vpn-gateway.sh
    - routing-delete-vpn-gateway.sh
    - torrent-main.sh
    - torrent-maintain-deluged.sh
    - vpn-main.sh
    - vpn-maintain-connection.sh
    - get-vpn-gateway-ip.sh
  tags:
    - nordvpn

- name: Ensure OpenVPN unit file override
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: /lib/systemd/system/openvpn-client@.service
    dest: /etc/systemd/system/openvpn-client@.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: Restart openvpn
  tags:
    - nordvpn

- name: Ensure ExecStartPre in unit file
  ansible.builtin.lineinfile:
    dest: /etc/systemd/system/openvpn-client@.service
    regexp: "^ExecStartPre"
    line: "ExecStartPre=/opt/vpn-manager/routing-add-vpn-gateway.sh"
    insertafter: "^ExecStart"
    state: present
  become: true
  tags:
    - nordvpn

- name: Ensure ExecStopPost in unit file
  ansible.builtin.lineinfile:
    dest: /etc/systemd/system/openvpn-client@.service
    regexp: "^ExecStopPost"
    line: "ExecStopPost=/opt/vpn-manager/routing-delete-vpn-gateway.sh"
    insertafter: "^ExecStartPre"
    state: present
  become: true
  tags:
    - nordvpn

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true
  tags:
    - nordvpn

- name: Ensure OpenVPN service is enabled and started
  ansible.builtin.systemd:
    name: openvpn-client@active
    enabled: true
    state: started
  become: true
  tags:
    - nordvpn