---
- name: Ensure unzip is installed
  become: true
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 3600  # Do not update if already done in the last hour.
    pkg:
      - unzip
  tags:
    - nordvpn

- name: Ensure OpenVPN is installed
  become: true
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 3600  # Do not update if already done in the last hour.
    pkg:
      - openvpn
  tags:
    - nordvpn